Nama  : Nadhifi Qurrunul B F H

Nim   : 1103204156

## Importing PyTorch

> **Note:**
PyTorch adalah sebuah framework machine learning open-source yang dikembangkan oleh Facebook. Framework ini sangat populer di kalangan peneliti dan praktisi machine learning karena menyediakan alat yang kuat untuk pengembangan model deep learning. Berikut adalah beberapa konsep fundamental dalam PyTorch:

1. **Tensor**: Tensor adalah struktur data dasar dalam PyTorch yang mirip dengan array atau matriks. Tensor dapat digunakan untuk merepresentasikan data numerik dalam berbagai dimensi.

2. **Autograd**: Autograd (Automatic Differentiation) adalah fitur PyTorch yang memungkinkan otomatis perhitungan gradien. Dengan autograd, PyTorch dapat melacak operasi-operasi yang dilakukan pada tensor dan menghitung gradien terhadap parameter secara otomatis.

3. **Module dan Model**: PyTorch menyediakan kelas Module untuk membangun arsitektur model. Model dapat dibangun dengan menurunkan kelas Module dan mendefinisikan metode forward untuk menggambarkan bagaimana data mengalir melalui model.

4. **Optimizers**: Optimizer digunakan untuk mengoptimalkan parameter-model dengan menyesuaikannya berdasarkan gradien yang dihitung selama proses pelatihan. PyTorch menyediakan berbagai optimizers seperti SGD (Stochastic Gradient Descent), Adam, dan lainnya.

5. **Loss Functions**: Fungsi kehilangan (loss function) digunakan untuk mengukur seberapa baik model bekerja pada tugas tertentu. PyTorch menyediakan berbagai fungsi kehilangan yang sesuai dengan berbagai jenis tugas, seperti klasifikasi dan regresi.

6. **DataLoader**: DataLoader memfasilitasi pemuatan dan pemrosesan data dalam batch selama pelatihan model. Ini membantu dalam efisiensi dan manajemen data selama proses pelatihan.

7. **CUDA dan GPU Acceleration**: PyTorch mendukung penggunaan GPU untuk percepatan komputasi. Ini memungkinkan pelatihan model dengan cepat menggunakan daya komputasi paralel GPU.

8. **Dynamic Computational Graph**: PyTorch menggunakan grafik komputasi dinamis, yang berarti grafik komputasi dapat diubah selama waktu eksekusi. Hal ini memberikan fleksibilitas yang lebih besar dalam membangun dan mengubah model.

9. **Ecosystem dan TorchScript**: PyTorch memiliki ekosistem yang kaya dengan berbagai pustaka dan alat pendukung seperti torchvision, torchtext, dan TorchScript. TorchScript memungkinkan serialisasi model PyTorch untuk inferensi yang lebih cepat.


In [ ]:
# Import library PyTorch
import torch

# Cetak versi PyTorch yang sedang digunakan
torch.__version__

'2.1.0+cu121'

## Introduction to tensors

Tensor adalah struktur data dasar dalam PyTorch, mirip dengan array atau matriks.

Tensor dapat merepresentasikan data numerik dalam berbagai dimensi.


### Creating tensors

> **Note:**  Berikut adalah tren yang akan dilakukan. Pengerjaan akan fokus pada penulisan kode secara spesifik. Namun, melibatkan pembacaan dan pengenalan terhadap dokumentasi PyTorch.


In [ ]:
#  Membuat tensor skalar dengan nilai 7
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#  Memeriksa jumlah dimensi dari tensor skalar (seharusnya 0 untuk skalar)
scalar.ndim

0

In [ ]:
# Mengekstrak angka Python dari tensor skalar (hanya berfungsi untuk tensor satu elemen)
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
#  Membuat tensor vektor dengan dua elemen (keduanya bernilai 7)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Memeriksa bentuk dari tensor vektor (ukuran 2)
vector.shape

torch.Size([2])

In [ ]:
# Membuat tensor matriks (2x2) dengan nilai yang ditentukan
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Memeriksa jumlah dimensi dari tensor matriks (seharusnya 2 untuk matriks)
MATRIX.ndim

2

In [ ]:
#Memeriksa bentuk dari tensor matriks (ukuran 2x2)
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Membuat tensor 3D dengan nilai yang ditentukan
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Memeriksa jumlah dimensi dari tensor 3D (seharusnya 3)
TENSOR.ndim

3

In [ ]:
# Memeriksa bentuk dari tensor 3D (ukuran 1x3x3)
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
Random tensors pada PyTorch fundamental adalah tensor yang nilainya ditentukan secara acak. Tensor ini dapat digunakan untuk berbagai keperluan, seperti:

* Membuat data pelatihan untuk model pembelajaran mendalam.
* Melakukan eksperimen dengan berbagai nilai parameter.
* Menghasilkan hasil yang tidak dapat diprediksi.*

PyTorch menyediakan berbagai fungsi untuk membuat random tensors. Salah satu fungsi yang paling umum digunakan adalah `torch.rand()`. Fungsi ini menghasilkan tensor dengan nilai acak yang mengikuti distribusi normal standar.

Berikut adalah contoh penggunaan fungsi `torch.rand()`:

```python
import torch

# Buat tensor acak dengan ukuran (3, 4, 5)
tensor = torch.rand((3, 4, 5))

# Cetak nilai tensor
print(tensor)
```

Output:

```
tensor([[0.1591, 0.0346, 0.7895, 0.5376, 0.8294],
        [0.3421, 0.5365, 0.9525, 0.9859, 0.6647],
        [0.5362, 0.6493, 0.2348, 0.8428, 0.6198]])
```

Selain `torch.rand()`, PyTorch juga menyediakan fungsi lain untuk membuat random tensors, seperti:

* `torch.randn()`: menghasilkan tensor dengan nilai acak yang mengikuti distribusi normal standar.
* `torch.randint()`: menghasilkan tensor dengan nilai acak yang merupakan bilangan bulat.
* `torch.randperm()`: menghasilkan tensor dengan urutan acak.

Pengguna dapat memilih fungsi yang sesuai dengan kebutuhannya.

In [ ]:
# Membuat tensor acak dengan ukuran (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7660, 0.3994, 0.4701, 0.5872],
         [0.6840, 0.4797, 0.0100, 0.7600],
         [0.9088, 0.1564, 0.3032, 0.3111]]),
 torch.float32)



*   Pada , sebuah tensor acak dengan ukuran (3, 4) dibuat menggunakan torch.rand(size=(3, 4)).

*   random_tensor dan tipe data tensor (random_tensor.dtype) dicetak untuk menampilkan hasilnya.



In [ ]:
# Membuat tensor acak dengan ukuran (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)



*   Pada , tensor acak dengan ukuran (224, 224, 3) dibuat.
*   random_image_size_tensor.shape digunakan untuk mengetahui bentuk (shape) dari tensor, dan random_image_size_tensor.ndim digunakan untuk mengetahui jumlah dimensi dari tensor tersebut.



### Zeros and ones

Dalam PyTorch, zeros dan ones adalah fungsi yang digunakan untuk membuat tensor dengan nilai nol atau satu. Fungsi zeros() membuat tensor dengan semua nilai nol, sedangkan fungsi ones() membuat tensor dengan semua nilai satu.

Berikut adalah contoh penggunaan fungsi zeros():

```python
import torch

# Membuat tensor dengan dimensi (3, 2)
tensor = torch.zeros((3, 2))

print(tensor)
```

Output:

```
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
```

Berikut adalah contoh penggunaan fungsi ones():

```python
import torch

# Membuat tensor dengan dimensi (3, 2)
tensor = torch.ones((3, 2))

print(tensor)
```

Output:

```
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
```

Fungsi zeros() dan ones() dapat digunakan untuk berbagai keperluan, seperti:

* Menginisialisasi nilai tensor
* Membuat tensor untuk digunakan sebagai target dalam pelatihan model pembelajaran mesin
* Membuat tensor untuk digunakan sebagai mask dalam operasi matematika

Pada PyTorch fundamental, fungsi zeros() dan ones() merupakan fungsi yang penting untuk dipelajari. Fungsi ini dapat digunakan untuk berbagai keperluan dasar dalam pembelajaran mendalam.

In [ ]:
# Membuat tensor dengan nilai semua elemen nol dan ukuran (3, 4)
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)



*   torch.zeros(size=(3, 4)) digunakan untuk membuat tensor dengan semua elemen bernilai nol dan ukuran (shape) (3, 4).

*   Tensor hasil (zeros) dan tipe datanya (zeros.dtype) dicetak.




In [ ]:
# Membuat tensor dengan nilai semua elemen satu dan ukuran (3, 4)
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)



*   torch.ones(size=(3, 4)) digunakan untuk membuat tensor dengan semua elemen bernilai satu dan ukuran (shape) (3, 4).
*   Tensor hasil (ones) dan tipe datanya (ones.dtype) dicetak.



### Creating a range and tensors like

 Untuk membuat tensor dengan rentang nilai tertentu atau berdasarkan pola tertentu, Anda dapat menggunakan fungsi PyTorch seperti `torch.arange`, `torch.linspace`, dan `torch.eye`. Berikut adalah contoh yang menunjukkan cara membuat tensor menggunakan fungsi-fungsi ini:

**Penjelasan:**

- **`torch.arange(start, end, step)`:** Membuat tensor 1D dengan nilai dari `start` ke `end-1` dengan langkah yang ditentukan.
- **`torch.linspace(start, end, steps)`:** Membuat tensor 1D dengan `steps` nilai yang berjarak sama antara `start` dan `end`.
- **`torch.eye(n)`:** Membuat matriks identitas berukuran `n x n` dengan elemen diagonal bernilai 1 dan sisanya 0.





In [ ]:
# Menggunakan torch.range(), yang sudah dinyatakan usang (deprecated)
zero_to_ten_deprecated = torch.range(0, 10)  # Catatan: ini mungkin menghasilkan kesalahan di masa depan

# Membuat rentang nilai dari 0 hingga 10 dengan langkah 1
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a49b364b1c92>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)  # Catatan: ini mungkin menghasilkan kesalahan di masa depan


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



*   Menggunakan torch.range() untuk membuat tensor dengan nilai dari 0 hingga 10.

*   Perlu dicatat bahwa torch.range() sudah usang (deprecated) dan mungkin menyebabkan kesalahan di masa depan.

*   Menggunakan torch.arange() untuk membuat tensor dengan nilai dari 0 hingga 10 dengan langkah 1.




In [ ]:
# Dapat juga membuat tensor berisi nol dengan bentuk yang sama seperti tensor lain
ten_zeros = torch.zeros_like(input=zero_to_ten)  # Akan memiliki bentuk yang sama
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


*   Menggunakan torch.zeros_like() untuk membuat tensor berisi nol dengan bentuk yang sama seperti zero_to_ten.


### Tensor datatypes

> **Note:**

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,          # Defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None,         # Defaults to None, which uses the default tensor type
                               requires_grad=False) # If True, operations performed on the tensor are recorded

# Menampilkan bentuk, tipe data, dan perangkat (device) dari tensor float_32_tensor
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))



*   Membuat tensor float_32_tensor dengan tipe data default float32, bentuk tensor diambil dari data yang diberikan (3 elemen), perangkat (device) default, dan tanpa gradient (requires_grad=False).
*   Menampilkan bentuk, tipe data, dan perangkat (device) dari tensor float_32_tensor.


In [ ]:
# Membuat tensor dengan tipe data float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half would also work

# Menampilkan tipe data dari tensor float_16_tensor
float_16_tensor.dtype

torch.float16



*   Membuat tensor float_16_tensor dengan tipe data float16.
*  Menampilkan tipe data dari tensor float_16_tensor.


## Getting information from tensors

**Getting information from tensors pada PyTorch fundamental adalah proses mengambil informasi dari tensor. Informasi yang dapat diambil dari tensor dapat berupa nilai tensor, ukuran tensor, dimensi tensor, atau tipe data tensor.**

Ada beberapa cara untuk mendapatkan informasi dari tensor di PyTorch. Salah satu cara yang paling umum adalah menggunakan atribut tensor. Setiap tensor memiliki beberapa atribut yang dapat digunakan untuk mendapatkan informasi tentang tensor tersebut.

Berikut adalah beberapa contoh penggunaan atribut tensor untuk mendapatkan informasi dari tensor:

Cara lain untuk mendapatkan informasi dari tensor adalah menggunakan metode tensor. Setiap tensor memiliki beberapa metode yang dapat digunakan untuk mendapatkan informasi tentang tensor tersebut.

Selain atribut dan metode tensor, Anda juga dapat menggunakan operator untuk mendapatkan informasi dari tensor. Misalnya, Anda dapat menggunakan operator `len()` untuk mendapatkan jumlah elemen dalam tensor.



In [ ]:
# Membuat tensor acak dengan ukuran (3, 4)
some_tensor = torch.rand(3, 4)

# Menampilkan detail tentang tensor
print(some_tensor)                                 # Menampilkan isi tensor
print(f"Shape of tensor: {some_tensor.shape}")      # Menampilkan bentuk (shape) tensor
print(f"Datatype of tensor: {some_tensor.dtype}")   # Menampilkan tipe data tensor
print(f"Device tensor is stored on: {some_tensor.device}")  # Menampilkan perangkat (device) tempat tensor disimpan (akan menggunakan CPU jika tidak ditentukan)


tensor([[0.4416, 0.5443, 0.9440, 0.1085],
        [0.7738, 0.8842, 0.5447, 0.5837],
        [0.6097, 0.1575, 0.2596, 0.9772]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu




*   Membuat tensor some_tensor dengan menggunakan torch.rand untuk mengisi tensor dengan nilai acak dan memberikan ukuran (shape) (3, 4).
*   Menampilkan berbagai detail tentang tensor seperti nilai-nilai tensor, bentuk (shape), tipe data, dan perangkat (device) tempat tensor disimpan.



## Manipulating tensors (tensor operations)
**Manipulating tensors (tensor operations) pada PyTorch fundamental adalah proses mengubah nilai, ukuran, dimensi, atau tipe data tensor.**

Ada banyak cara untuk memanipulasi tensor di PyTorch. Salah satu cara yang paling umum adalah menggunakan operator matematika. Operator matematika dapat digunakan untuk melakukan operasi aritmatika pada tensor, seperti penjumlahan, pengurangan, perkalian, dan pembagian.

Selain operator matematika,juga dapat menggunakan fungsi untuk memanipulasi tensor. Fungsi-fungsi ini dapat digunakan untuk melakukan operasi yang lebih kompleks, seperti transposisi, reshaping, dan slicing.


### Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

They work just as you think they would.

In [ ]:
# Creating a tensor of values and adding a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10
# Output: tensor([11, 12, 13])

tensor([11, 12, 13])

In [ ]:
# Multiplying the tensor by 10
tensor

tensor([10, 20, 30])

In [ ]:
# Subtracting and reassigning
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Adding and reassigning
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
#  Using torch.multiply() function
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


**Penjelasan:**
1. **Penambahan Nilai ke Tensor ([23]):**
   - Membuat tensor `tensor` dengan nilai [1, 2, 3].
   - Menambahkan nilai 10 ke setiap elemen tensor.

2. **Perkalian Tensor dengan Angka ([24]):**
   - Mengalikan setiap elemen tensor dengan 10.

3. **Menampilkan Tensor Asli ([25]):**
   - Menampilkan tensor asli tanpa perubahan.

4. **Pengurangan dan Pembaruan Tensor ([26] dan [27]):**
   - Mengurangkan nilai 10 dan kemudian menambahkan nilai 10 ke setiap elemen tensor, melakukan pembaruan nilai.

5. **Penggunaan Fungsi PyTorch untuk Perkalian ([28]):**
   - Menggunakan fungsi PyTorch `torch.multiply()` untuk mengalikan tensor dengan 10.

6. **Menampilkan Tensor Asli ([29]):**
   - Menampilkan tensor asli tanpa perubahan setelah operasi perkalian.

7. **Perkalian Elemen-wise Menggunakan Operator * ([30]):**
   - Melakukan perkalian elemen-wise (setiap elemen dikalikan dengan elemen yang setara) dan menampilkan hasilnya.
   - Hasilnya adalah tensor baru dengan elemen hasil perkalian.
   - Operator `*` lebih umum digunakan daripada fungsi PyTorch untuk perkalian.

**Catatan:**
- Operasi tensor dapat dilakukan dengan operator matematika standar atau menggunakan fungsi PyTorch.
- Tensor asli tidak berubah kecuali jika direassign dengan hasil operasi.

### Matrix multiplication (is all you need)

**Matrix multiplication pada PyTorch fundamental adalah operasi matematika yang mengalikan dua matriks. Matriks adalah struktur data dua dimensi yang terdiri dari elemen-elemen. Matriks dapat digunakan untuk mewakili berbagai macam data, seperti transformasi linear, hubungan antara variabel, dan data kuantitatif.**

Dalam PyTorch, matrix multiplication dapat dilakukan menggunakan fungsi `torch.matmul()`. Fungsi ini menerima dua matriks sebagai input dan menghasilkan matriks sebagai output.


* Dimensi pertama dari matriks pertama harus sama dengan dimensi kedua dari matriks kedua.
* Dimensi keluaran matriks perkalian adalah jumlah elemen dalam dimensi pertama dari matriks pertama dan dimensi pertama dari matriks kedua.

Berikut adalah beberapa contoh lain dari matrix multiplication:

* Matriks perkalian dapat digunakan untuk mewakili transformasi linear. Misalnya, matriks perkalian dapat digunakan untuk memutar, mencerminkan, atau menggeser gambar.
* Matriks perkalian dapat digunakan untuk mewakili hubungan antara variabel. Misalnya, matriks perkalian dapat digunakan untuk memprediksi nilai variabel Y dari nilai variabel X.
* Matriks perkalian dapat digunakan untuk melakukan berbagai macam operasi matematika, seperti penjumlahan, pengurangan, dan perkalian.

Matrix multiplication adalah operasi matematika yang penting yang banyak digunakan dalam berbagai bidang, termasuk pembelajaran mesin, computer vision, dan kecerdasan buatan.


In [ ]:
import torch
# Membuat tensor dengan nilai [1, 2, 3]
tensor = torch.tensor([1, 2, 3])
# Menampilkan bentuk (shape) tensor
tensor.shape

torch.Size([3])

In [ ]:
# Operasi perkalian elemen-wise pada tensor
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Operasi perkalian matriks (dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Alternatif penggunaan simbol "@" untuk perkalian matriks (not recommended)
tensor @ tensor

tensor(14)

In [ ]:
%%time
# Pengukuran waktu untuk operasi perkalian matriks dengan perulangan
# (disarankan untuk menghindari penggunaan perulangan for dalam operasi tensor karena komputasionalnya mahal)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 1.67 ms


tensor(14)

In [ ]:
%%time
# Pengukuran waktu untuk operasi perkalian matriks dengan torch.matmul
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 7 µs, total: 40 µs
Wall time: 43.2 µs


tensor(14)


**Note:**
1. **Pembuatan Tensor dan Menampilkan Bentuk ([1] dan [2]):**
   - Membuat tensor `tensor` dengan nilai [1, 2, 3].
   - Menampilkan bentuk (shape) tensor, yang dalam hal ini adalah `[3]`.

2. **Operasi Perkalian Elemen-wise dan Matriks ([3] hingga [6]):**
   - Melakukan perkalian elemen-wise pada tensor dengan dirinya sendiri.
   - Melakukan operasi perkalian matriks (dot product) menggunakan `torch.matmul`.
   - Alternatif penggunaan simbol "@" untuk perkalian matriks, walaupun tidak disarankan.

3. **Pengukuran Waktu untuk Operasi Perkalian Matriks ([7] dan [9]):**
   - Menggunakan `%%time` untuk mengukur waktu eksekusi operasi perkalian matriks dengan perulangan for.
   - Melakukan operasi perkalian matriks dengan `torch.matmul` dan mengukur waktu eksekusinya.
   - Hasilnya menunjukkan bahwa operasi dengan `torch.matmul` lebih efisien dan lebih cepat.

## One of the most common errors in deep learning (shape errors)
Salah satu kesalahan umum dalam pembelajaran mendalam (deep learning) dengan PyTorch adalah kesalahan pada penanganan dimensi atau bentuk tensor. Beberapa kesalahan yang sering terjadi antara lain:

1. **Mismatch Dimensi/Tensor Shape:**
   - Kesalahan ini terjadi ketika dimensi tensor yang diharapkan oleh suatu operasi tidak sesuai dengan dimensi tensor yang diberikan sebagai input. Misalnya, matriks yang diharapkan memiliki dimensi (m, n), tetapi input yang diberikan memiliki dimensi yang tidak sesuai.

2. **Batch Size Tidak Konsisten:**
   - Dalam pelatihan model deep learning, batch size harus konsisten di seluruh data set. Kesalahan dapat terjadi jika ada variasi dalam batch size antara iterasi, yang dapat menyebabkan masalah dalam komputasi gradien.

3. **Perhatikan Input Model:**
   - Pastikan input yang diberikan ke model sesuai dengan input yang diharapkan oleh arsitektur model. Kesalahan ini dapat muncul jika ada ketidakcocokan antara struktur input dan model yang diharapkan.

4. **Penanganan Nilai Nol atau NaN (Not a Number):**
   - Terkadang, dalam proses pelatihan, nilai-nilai NaN atau infinity dapat muncul. Ini bisa terjadi jika ada pembagian dengan nol atau operasi lain yang menyebabkan nilai yang tidak terdefinisi. Memeriksa dan mengelola ini dapat membantu menghindari masalah tersebut.

5. **Memastikan Tipe Data yang Benar:**
   - Pastikan bahwa tipe data tensor yang digunakan sesuai dengan yang diharapkan oleh operasi atau model. Kesalahan dapat terjadi jika tipe data tidak sesuai.

6. **Inisialisasi Bobot yang Tidak Tepat:**
   - Inisialisasi bobot model dengan benar sangat penting. Jika bobot diinisialisasi dengan nilai yang terlalu kecil atau terlalu besar, atau dengan distribusi yang tidak tepat, ini dapat menghambat konvergensi model.

7. **Pemahaman Fungsi Loss:**
   - Pastikan pemahaman yang baik tentang fungsi loss yang digunakan. Kesalahan dalam penggunaan fungsi loss dapat menyebabkan hasil yang tidak akurat.

Untuk menghindari kesalahan-kesalahan ini, sangat penting untuk memahami dengan baik dokumentasi PyTorch dan secara cermat memeriksa kode Anda, termasuk penanganan dimensi tensor, tipe data, dan parameter lainnya. Memiliki pemahaman yang kuat tentang dasar-dasar PyTorch dan konsep deep learning akan membantu mencegah dan menemukan kesalahan dengan lebih efisien.

In [ ]:
# Membuat tensor_A dan tensor_B dengan tipe data float32
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# Melakukan transpose pada tensor_B agar perkalian menjadi valid
tensor_B_transposed = tensor_B.t()

# Melakukan perkalian matriks menggunakan torch.matmul
result = torch.matmul(tensor_A, tensor_B_transposed)
print(result)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [ ]:
# Menampilkan isi dari tensor_A dan tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# Menampilkan isi dari tensor_A dan tensor_B.T (transpose)
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# Operasi perkalian berhasil ketika tensor_B di-transpose
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm adalah singkatan dari matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Mengatur seed agar hasil reproduktif
torch.manual_seed(42)

# Membuat layer linear dengan PyTorch
linear = torch.nn.Linear(in_features=2, # in_features = sesuai dengan dimensi inner input
                         out_features=6) # out_features = jumlah neuron pada layer
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


**Catatan dan Penjelasan:**
1. **Pembuatan Tensor dan Transpose ([1] hingga [3]):**
   - Dua tensor, `tensor_A` dan `tensor_B`, dibuat dengan tipe data float32.
   - `tensor_B` di-transpose agar operasi perkalian matriks menjadi valid.

2. **Operasi Perkalian Matriks ([5] hingga [15]):**
   - Melakukan operasi perkalian matriks antara `tensor_A` dan transpose dari `tensor_B`.
   - Menampilkan isi `tensor_A` dan `tensor_B`.
   - Menampilkan isi `tensor_A` dan transpose dari `tensor_B`.
   - Menunjukkan bahwa operasi perkalian matriks valid ketika `tensor_B` di-transpose.

3. **Penggunaan torch.nn.Linear ([17] hingga [26]):**
   - Membuat layer linear dengan PyTorch.
   - Menggunakan layer linear untuk melakukan operasi matrix multiplication dengan tensor `tensor_A`.
   - Menampilkan ukuran input dan output dari operasi tersebut.
   - Penetapan seed memastikan hasil yang dapat direproduksi.

### Finding the min, max, mean, sum, etc (aggregation)
Dalam PyTorch, Anda dapat menggunakan fungsi-fungsi bawaan untuk menemukan nilai minimum, maksimum, rata-rata, dan jumlah dari elemen-elemen tensor. Berikut adalah beberapa contoh penggunaan fungsi-fungsi tersebut:

Pastikan untuk memperhatikan tipe data tensor, karena dalam beberapa kasus, Anda mungkin perlu mengkonversi tipe data ke float terlebih dahulu untuk menghindari kesalahan atau hasil yang tidak diinginkan. Juga, perhatikan bahwa metode `.item()` digunakan untuk mendapatkan nilai skalar dari tensor dengan satu elemen.



In [ ]:
# Membuat tensor menggunakan torch.arange() dengan nilai awal 0, akhir 100 (tidak termasuk), dan langkah 10
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Menampilkan nilai maksimum dari tensor x
print(f"Maximum: {x.max()}")

# Menampilkan mean dari tensor x (perlu diubah tipe datanya menjadi float32)
# print(f"Mean: {x.mean()}")  # Baris ini akan menghasilkan error
print(f"Mean: {x.type(torch.float32).mean()}")  # Harus mengubah tipe data menjadi float32

# Menampilkan jumlah (sum) dari semua elemen tensor x
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Penggunaan fungsi max, min, mean, dan sum dengan torch
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

**Catatan dan Penjelasan:**
1. **Pembuatan Tensor dengan arange() ([1]):**
   - `torch.arange(0, 100, 10)` digunakan untuk membuat tensor `x` dengan nilai awal 0, akhir 100 (tidak termasuk), dan langkah 10.

2. **Operasi Statistik pada Tensor ([3] hingga [12]):**
   - `x.min()` digunakan untuk mendapatkan nilai minimum dari tensor `x`.
   - `x.max()` digunakan untuk mendapatkan nilai maksimum dari tensor `x`.
   - `x.type(torch.float32).mean()` digunakan untuk mendapatkan nilai mean dari tensor `x` setelah diubah tipe datanya menjadi float32.
   - `x.sum()` digunakan untuk mendapatkan jumlah (sum) dari semua elemen tensor `x`.

3. **Penggunaan Fungsi Torch untuk Statistik ([14]):**
   - `torch.max(x)`, `torch.min(x)`, `torch.mean(x.type(torch.float32))`, dan `torch.sum(x)` digunakan untuk mendapatkan nilai maksimum, minimum, mean, dan jumlah (sum) dari tensor `x` menggunakan fungsi PyTorch.

**Note:**
- Operasi statistik seperti min, max, mean, dan sum dapat dilakukan langsung pada tensor.
- Untuk menggunakan mean, tipe data tensor perlu diubah terlebih dahulu menjadi float32 karena mean tidak dapat dihitung pada tensor integer.

### Positional min/max



In [ ]:
# Membuat tensor dengan nilai dari 10 hingga 90 dengan langkah 10
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Mendapatkan indeks dari nilai maksimum dan minimum dalam tensor
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


**Penjelasan:**
1. **Pembuatan Tensor ([1]):**
   - `torch.arange(10, 100, 10)` digunakan untuk membuat tensor `tensor` dengan nilai mulai dari 10, hingga 90 dengan langkah 10.

2. **Mendapatkan Indeks Maksimum dan Minimum ([4] dan [5]):**
   - `tensor.argmax()` digunakan untuk mendapatkan indeks dari nilai maksimum dalam tensor.
   - `tensor.argmin()` digunakan untuk mendapatkan indeks dari nilai minimum dalam tensor.

### Change tensor datatype



In [ ]:
# Membuat tensor dan memeriksa tipe datanya
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# Membuat tensor dengan tipe data float16
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Membuat tensor dengan tipe data int8
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Penjelasan:**
1. **Pembuatan Tensor dan Pemeriksaan Tipe Data ([1] dan [3]):**
   - `torch.arange(10., 100., 10.)` digunakan untuk membuat tensor `tensor` dengan nilai dari 10 hingga 90 dengan langkah 10, dan tipe data float32 (default).
   - `tensor.dtype` digunakan untuk mendapatkan tipe data tensor tersebut.

2. **Membuat Tensor dengan Tipe Data Float16 ([5] dan [6]):**
   - `tensor.type(torch.float16)` digunakan untuk membuat tensor baru dengan tipe data float16 dari tensor asli `tensor`.

3. **Membuat Tensor dengan Tipe Data Int8 ([8] dan [9]):**
   - `tensor.type(torch.int8)` digunakan untuk membuat tensor baru dengan tipe data int8 dari tensor asli `tensor`.

### Reshaping, stacking, squeezing and unsqueezing
Di PyTorch, operasi seperti reshaping, stacking, squeezing, dan unsqueezing adalah metode penting untuk memanipulasi dimensi dan bentuk tensor. Berikut adalah penjelasan singkat untuk setiap operasi tersebut:

1. **Reshaping:**
   - Reshaping adalah proses mengubah bentuk (shape) dari suatu tensor. Dalam PyTorch, operasi `view` dapat digunakan untuk melakukan reshaping. Misalnya, jika Anda memiliki tensor 2D dengan ukuran (m, n), Anda dapat menggunakan `view` untuk mengubahnya menjadi tensor 1D atau tensor 2D dengan ukuran lainnya.

2. **Stacking:**
   - Stacking mengacu pada penggabungan beberapa tensor menjadi satu tensor. Operasi `torch.stack` dapat digunakan untuk menumpuk tensor-tensor tersebut. Ini dapat dilakukan baik pada dimensi yang sudah ada maupun dimensi baru.

3. **Squeezing:**
   - Squeezing digunakan untuk mengurangkan dimensi dengan ukuran 1 dari suatu tensor. Misalnya, jika Anda memiliki tensor dengan dimensi (1, m, n), Anda dapat menggunakan `squeeze` untuk menghilangkan dimensi yang memiliki ukuran 1.

4. **Unsqueezing:**
   - Unsqueezing adalah kebalikan dari squeezing. Ini digunakan untuk menambahkan dimensi dengan ukuran 1 pada suatu tensor. Operasi `unsqueeze` dapat digunakan untuk ini.

Operasi-operasi ini sangat berguna ketika Anda bekerja dengan model deep learning dan perlu memanipulasi bentuk tensor untuk keperluan seperti pengolahan data, konstruksi model, atau operasi matematika tertentu.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# Menampilkan informasi tensor sebelumnya dan menghapus dimensi tambahan dari x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
# Menambah dimensi tambahan dengan unsqueeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
# Membuat tensor dengan bentuk tertentu, dan mengubah urutan sumbu
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Catatan:**
- Operasi seperti `reshape`, `view`, `squeeze`, dan `unsqueeze` dapat digunakan untuk mengubah bentuk dan dimensi tensor.
- Fungsi-fungsi ini berguna dalam proses persiapan data untuk model machine learning.

## Indexing (selecting data from tensors)

Dalam konteks PyTorch, indexing merujuk pada proses memilih atau mengakses elemen-elemen tertentu dari tensor. PyTorch menggunakan konsep indexing yang mirip dengan NumPy, yang memungkinkan Anda untuk memanipulasi dan mengakses data dalam tensor dengan cara yang fleksibel. Berikut adalah beberapa konsep dasar terkait indexing pada PyTorch:

1. **Indexing dengan Angka Bulat:**
   - Anda dapat menggunakan angka bulat untuk mengakses elemen tertentu dari tensor. Misalnya, jika `x` adalah tensor, `x[0]` akan mengakses elemen pertama, dan `x[1]` akan mengakses elemen kedua.

2. **Slicing:**
   - Seperti NumPy, PyTorch mendukung slicing untuk memperoleh sebagian dari tensor. Misalnya, `x[1:4]` akan memberikan sebagian tensor dari indeks 1 hingga 3.

3. **Indexing Multidimensional:**
   - Untuk tensor multidimensional, Anda dapat menggunakan indeks terpisah untuk setiap dimensi. Misalnya, `x[0, 1]` akan mengakses elemen di baris pertama dan kolom kedua.

4. **Indexing dengan Boolean Masks:**
   - Anda dapat menggunakan tensor boolean sebagai mask untuk memilih elemen-elemen tertentu. Misalnya, `x[x > 0]` akan menghasilkan tensor yang hanya berisi elemen-elemen yang positif.

5. **Indexing dengan List atau Tensor Indeks:**
   - Anda dapat menggunakan list atau tensor sebagai indeks untuk memilih elemen-elemen tertentu. Misalnya, `indices = [0, 2, 4]` dan kemudian `x[indices]` akan menghasilkan tensor dengan elemen di indeks 0, 2, dan 4.


In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Mendapatkan semua nilai dari dimensi ke-0 dan indeks ke-0 dari dimensi ke-1
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Mendapatkan semua nilai dari dimensi ke-0 dan indeks ke-1 dari dimensi ke-2
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Mendapatkan semua nilai dari dimensi ke-0 dan hanya nilai indeks ke-1 dari dimensi ke-1 dan ke-2
x[:, 1, 1]

tensor([5])

In [ ]:
# Mendapatkan indeks ke-0 dari dimensi ke-0 dan ke-1 serta semua nilai dari dimensi ke-2
x[0, 0, :]  # sama dengan x[0][0]

tensor([1, 2, 3])

**Catatan:**
- Indeksing pada tensor dilakukan dengan menggunakan tanda bracket `[]` untuk mengakses nilai pada dimensi yang diinginkan.
- Memahami indeksing pada tensor penting untuk manipulasi dan pemrosesan data menggunakan PyTorch.

## PyTorch tensors & NumPy



In [ ]:
# Membuat array NumPy dan mengonversinya menjadi tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0) # Membuat array NumPy dari 1.0 hingga 7.0
tensor = torch.from_numpy(array) # Mengonversi array NumPy menjadi tensor
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Mengubah array NumPy, tetapi tetap menggunakan tensor yang sama
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Mengonversi tensor menjadi array NumPy
tensor = torch.ones(7) # Membuat tensor yang berisi tujuh elemen dengan nilai satu dan tipe data float32
numpy_tensor = tensor.numpy() # Mengonversi tensor menjadi array NumPy
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Mengubah tensor, tetapi tetap menggunakan array NumPy yang sama
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Penjelasan:**
1. **Membuat Array NumPy dan Mengonversi Menjadi Tensor ([3] dan [4]):**
   - `np.arange(1.0, 8.0)` digunakan untuk membuat array NumPy dari 1.0 hingga 7.0.
   - `torch.from_numpy(array)` digunakan untuk mengonversi array NumPy menjadi tensor PyTorch.

2. **Mengubah Array NumPy Tetapi Tetap Menggunakan Tensor ([6] dan [7]):**
   - `array = array + 1` digunakan untuk menambahkan 1 ke setiap elemen array NumPy.
   - Meskipun array NumPy diubah, tensor yang dibuat dari array tersebut tetap terpengaruh, karena tensor dan array berbagi memori yang sama.

3. **Mengonversi Tensor Menjadi Array NumPy ([9] dan [10]):**
   - `torch.ones(7)` digunakan untuk membuat tensor yang berisi tujuh elemen dengan nilai satu dan tipe data float32.
   - `tensor.numpy()` digunakan untuk mengonversi tensor PyTorch menjadi array NumPy.

4. **Mengubah Tensor Tetapi Tetap Menggunakan Array NumPy yang Sama ([12] dan [13]):**
   - `tensor = tensor + 1` digunakan untuk menambahkan 1 ke setiap elemen tensor.
   - Meskipun tensor diubah, array NumPy yang dibuat dari tensor tersebut tetap terpengaruh, karena tensor dan array berbagi memori yang sama.

**Catatan:**
- Menggunakan `torch.from_numpy()` atau `tensor.numpy()` memungkinkan berbagi memori antara tensor PyTorch dan array NumPy, sehingga perubahan pada satu entitas akan tercermin pada entitas lainnya.
- Perlu diperhatikan bahwa tipe data array NumPy dan tensor PyTorch perlu kompatibel agar konversi dapat dilakukan.

## Reproducibility (trying to take the random out of random)



In [ ]:
import torch
# Membuat dua tensor acak
random_tensor_A = torch.rand(3, 4)  # Membuat tensor acak A berukuran 3x4
random_tensor_B = torch.rand(3, 4)  # Membuat tensor acak B berukuran 3x4

print(f"Tensor A:\n{random_tensor_A}\n")  # Mencetak tensor A
print(f"Tensor B:\n{random_tensor_B}\n")  # Mencetak tensor B
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B  # Memeriksa apakah nilai elemen di Tensor A sama dengan Tensor B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random
# Set the random seed
RANDOM_SEED=42  # Menetapkan seed acak untuk reproduktibilitas
torch.manual_seed(seed=RANDOM_SEED)  # Menetapkan seed untuk generator angka acak PyTorch
random_tensor_C = torch.rand(3, 4)  # Membuat tensor acak C berukuran 3x4

# Harus mereset seed setiap kali rand() baru dipanggil
# Tanpa ini, tensor_D akan berbeda dari tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)  # Menetapkan seed untuk generator angka acak PyTorch
random_tensor_D = torch.rand(3, 4)  # Membuat tensor acak D berukuran 3x4

print(f"Tensor C:\n{random_tensor_C}\n")  # Mencetak tensor C
print(f"Tensor D:\n{random_tensor_D}\n")  # Mencetak tensor D
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D  # Memeriksa apakah nilai elemen di Tensor C sama dengan Tensor D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Penjelasan:**
1. **Membuat Dua Tensor Acak ([3] hingga [7]):**
   - `torch.rand(3, 4)` digunakan untuk membuat dua tensor acak (`random_tensor_A` dan `random_tensor_B`) dengan ukuran 3x4.

2. **Pembandingan Elemen Tensor A dan B ([9]):**
   - `random_tensor_A == random_tensor_B` digunakan untuk memeriksa apakah nilai elemen di `random_tensor_A` sama dengan nilai elemen di `random_tensor_B`. Hasilnya berupa tensor Boolean yang menunjukkan kecocokan elemen.

3. **Mengatur Seed Acak untuk Reproduktibilitas ([11] hingga [18]):**
   - `RANDOM_SEED=42` digunakan sebagai seed acak untuk memastikan hasil yang dapat direproduksi.
   - `torch.manual_seed(seed=RANDOM_SEED)` digunakan untuk menetapkan seed untuk generator angka acak PyTorch.
   - `torch.random.manual_seed(seed=RANDOM_SEED)` digunakan untuk menetapkan seed yang sama pada generator acak PyTorch lainnya.
   - `torch.rand(3, 4)` dan `torch.rand(3, 4)` digunakan untuk membuat dua tensor acak (`random_tensor_C` dan `random_tensor_D`) dengan ukuran yang sama.
  
4. **Pembandingan Elemen Tensor C dan D ([20]):**
   - `random_tensor_C == random_tensor_D` digunakan untuk memeriksa apakah nilai elemen di `random_tensor_C` sama dengan nilai elemen di `random_tensor_D`. Hasilnya berupa tensor Boolean yang menunjukkan kecocokan elemen.

**Catatan:**
- Menggunakan seed acak memastikan bahwa generator angka acak memberikan nilai yang sama setiap kali dijalankan, sehingga hasil dapat direproduksi.
- Seed yang berbeda akan menghasilkan nilai acak yang berbeda, dan seed yang sama akan menghasilkan nilai acak yang sama.

## Running tensors on GPUs (and making faster computations)

Algoritma pembelajaran mendalam memerlukan banyak operasi numerik.

Dan secara default operasi ini sering dilakukan pada CPU (unit pengolah komputer).

Namun, ada perangkat keras umum lainnya yang disebut GPU (unit pemrosesan grafis), yang seringkali jauh lebih cepat dalam melakukan jenis operasi tertentu yang dibutuhkan jaringan saraf (perkalian matriks) dibandingkan CPU.

Komputer Anda mungkin memilikinya.

Jika demikian, Anda harus menggunakannya kapan pun Anda bisa untuk melatih jaringan saraf karena kemungkinan besar ini akan mempercepat waktu pelatihan secara dramatis.

Ada beberapa cara untuk pertama mendapatkan akses ke GPU dan kedua membuat PyTorch menggunakan GPU tersebut.





### 1. Getting a GPU




In [ ]:
!nvidia-smi

Thu Jan  4 14:13:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--


Potongan kode di atas menunjukkan langkah-langkah untuk menggunakan GPU dengan PyTorch. Pada bagian pertama, [70], digunakan perintah !nvidia-smi untuk menampilkan informasi tentang GPU yang tersedia. Outputnya menunjukkan adanya GPU Tesla T4 yang dapat digunakan.



### 2. Getting PyTorch to run on the GPU




In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

Berikutnya, [71], kode Python menggunakan perpustakaan PyTorch untuk memeriksa ketersediaan GPU dengan torch.cuda.is_available(). Hasilnya adalah True, menandakan bahwa GPU dapat digunakan. Kemudian, [72], sebuah variabel device ditetapkan sebagai "cuda" jika GPU tersedia, dan "cpu" jika tidak.

### 3. Putting tensors (and models) on the GPU



In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Pada bagian [73], dilakukan pengecekan jumlah perangkat GPU dengan torch.cuda.device_count(), dan outputnya menunjukkan satu perangkat GPU yang terdeteksi.


Selanjutnya, [74], sebuah tensor PyTorch dibuat secara default di CPU. Kemudian, dengan menggunakan metode .to(device), tensor tersebut dipindahkan ke GPU jika tersedia. Hasilnya adalah tensor yang sekarang berada di GPU, dan perangkatnya ditampilkan.

### 4. Moving tensors back to the CPU


In [ ]:
import torch

# Assuming tensor_on_gpu is your tensor on GPU
tensor_on_gpu = tensor_on_gpu.to('cpu')  # Move tensor from GPU to CPU
numpy_array = tensor_on_gpu.numpy()

# Now you can use numpy_array as a NumPy array
numpy_array = tensor_on_gpu.cpu().numpy()


In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

Bagian [75] dan [76] menunjukkan cara memindahkan kembali tensor dari GPU ke CPU. Ini dapat dilakukan dengan menggunakan metode .to('cpu') atau .cpu(). Juga, cara lainnya adalah dengan mengonversi tensor menjadi array NumPy dengan .numpy().